version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: stocky-app
    container_name: stocky-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - stocky

  nginx:
    image: nginx:alpine
    container_name: stocky-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - stocky

  db:
    image: mysql:8.0
    container_name: stocky-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - stocky

  redis:
    image: redis:alpine
    container_name: stocky-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - stocky

networks:
  stocky:
    driver: bridge

volumes:
  dbdata:
    driver: local
